# Generated by Django 3.2.5 on 2021-11-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_chat_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='performer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
