# Generated by Django 3.2.5 on 2021-11-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211104_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_chat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_message_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
