# Generated by Django 3.2.3 on 2021-11-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211104_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='requests_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_chat_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_message_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='music',
            name='performer',
            field=models.CharField(default='@Top_MusicsBot', max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(default='@Top_MusicsBot', max_length=255),
        ),
    ]
