# Generated by Django 3.2.5 on 2021-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211115_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='keyboard_style',
            field=models.IntegerField(default=1),
        ),
    ]
