# Generated by Django 3.2.7 on 2022-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220201_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='to_chanel_chat_id',
            field=models.IntegerField(verbose_name='Основной канал'),
        ),
    ]
