# Generated by Django 4.0.2 on 2022-02-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_parser_from_chanels_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='coments',
            field=models.TextField(default='', verbose_name='Коментарии'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='keywords',
            field=models.TextField(verbose_name='Минус слова'),
        ),
    ]
