# Generated by Django 3.2.7 on 2022-02-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_parser_coments_alter_parser_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='from_chanels_chat_id',
            field=models.IntegerField(verbose_name='Донор чат'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='keywords',
            field=models.TextField(verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='to_chanel_chat_id',
            field=models.IntegerField(verbose_name='Основной чат'),
        ),
    ]
