# Generated by Django 3.2.7 on 2022-02-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20220216_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='coments',
        ),
    ]
