# Generated by Django 3.2.3 on 2022-07-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_subchats_subchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='link_from_chanel',
        ),
    ]
