# Generated by Django 3.2.3 on 2022-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_parser_link_from_chanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='notlink',
            field=models.BooleanField(default=False, verbose_name='Без ссылок'),
        ),
    ]
