# Generated by Django 3.2.3 on 2022-07-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20220720_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='keywords',
            field=models.TextField(verbose_name='Ключевые слова'),
        ),
    ]
