# Generated by Django 3.2.3 on 2022-07-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_parser_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='keywords',
            field=models.TextField(default=None, verbose_name='Ключевые слова'),
        ),
    ]
