# Generated by Django 3.2.3 on 2022-07-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_parser_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='pause',
            field=models.FloatField(default=0),
        ),
    ]
