# Generated by Django 3.2.3 on 2022-08-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20220720_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='ex_link',
        ),
        migrations.RemoveField(
            model_name='parser',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='parser',
            name='notlink',
        ),
        migrations.RemoveField(
            model_name='parser',
            name='pause',
        ),
    ]
