# Generated by Django 3.2.3 on 2022-08-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='chat_id',
            field=models.IntegerField(),
        ),
    ]
