# Generated by Django 3.1.6 on 2023-01-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20220809_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Текст')),
                ('message_id', models.IntegerField()),
                ('urls', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, verbose_name='Команда')),
                ('message_id', models.IntegerField()),
                ('urls', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Не трогать!!')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Parser',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='SubChat',
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
