# Generated by Django 3.1.6 on 2023-01-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20230111_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': 'Командa', 'verbose_name_plural': 'Команды'},
        ),
    ]
