# Generated by Django 3.1.6 on 2023-01-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20230111_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buttons',
            new_name='Button',
        ),
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
    ]
