# Generated by Django 3.1.6 on 2023-01-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20230111_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='command',
            new_name='name',
        ),
    ]
