# Generated by Django 3.1.6 on 2023-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20230111_0248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.AddField(
            model_name='botuser',
            name='ans1',
            field=models.TextField(default='Неизвестно'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='ans2',
            field=models.TextField(default='Неизвестно'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='ans3',
            field=models.TextField(default='Неизвестно'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='ans4',
            field=models.TextField(default='Неизвестно'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='ans5',
            field=models.TextField(default='Неизвестно'),
        ),
    ]
