# Generated by Django 3.1.6 on 2023-06-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_remove_botuser_ans5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.IntegerField(unique=True, verbose_name='Айди'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='ответ')),
                ('pont', models.FloatField(verbose_name='Балл')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase', to='backend.test')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
