# Generated by Django 3.1.6 on 2023-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20230602_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='sex',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], default='Male', max_length=255, verbose_name='Пол'),
        ),
    ]
