# Generated by Django 3.1.6 on 2023-06-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20230606_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Суб категория', 'verbose_name_plural': 'Суб категории'},
        ),
    ]
