# Generated by Django 3.1.6 on 2023-06-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_auto_20230606_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='text_1',
            field=models.TextField(default='-', verbose_name='0% - 33%'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='text_2',
            field=models.TextField(default='-', verbose_name='33% - 66%'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='text_3',
            field=models.TextField(default='-', verbose_name='66% - 100%'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subcategory', verbose_name='Суб категория'),
        ),
    ]
