# Generated by Django 4.2.2 on 2023-06-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_alter_botuser_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('point', models.FloatField(default=0, verbose_name='Балл')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Суб категория', 'verbose_name_plural': 'Суб категории'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='text',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default=12, max_length=255, verbose_name='Названия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='text_1',
            field=models.TextField(default='-', verbose_name='0% - 33%'),
        ),
        migrations.AddField(
            model_name='test',
            name='text_2',
            field=models.TextField(default='-', verbose_name='33% - 66%'),
        ),
        migrations.AddField(
            model_name='test',
            name='text_3',
            field=models.TextField(default='-', verbose_name='66% - 100%'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.question', verbose_name='Вопрос'),
        ),
    ]
