# Generated by Django 4.2.2 on 2023-06-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_answers_question_alter_test_options_remove_test_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
