# Generated by Django 4.2.2 on 2023-06-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_rename_category_question_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='user',
            new_name='users',
        ),
    ]
