# Generated by Django 4.2.2 on 2023-06-24 05:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_question_users_test_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='backend.botuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='backend.botuser', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='AcceptedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.botuser', verbose_name='Пользователь')),
            ],
        ),
    ]
