# Generated by Django 4.2.2 on 2023-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_mailing_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default='-', verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='users',
            field=models.ManyToManyField(blank=True, to='backend.botuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='paid_choice',
            field=models.CharField(blank=True, choices=[('male', 'Мужчинам'), ('female', 'Женщинам'), ('all', 'Всем')], default='all', max_length=20, null=True, verbose_name='Выбор получателей'),
        ),
        migrations.AlterField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(blank=True, to='backend.botuser', verbose_name='Пользователь'),
        ),
    ]
