# Generated by Django 4.2.2 on 2023-07-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_test_description_alter_answers_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedtest',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='text_4',
            field=models.TextField(blank=True, null=True, verbose_name='4'),
        ),
        migrations.AddField(
            model_name='test',
            name='text_5',
            field=models.TextField(blank=True, null=True, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='test',
            name='text_1',
            field=models.TextField(default='-', verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='test',
            name='text_2',
            field=models.TextField(blank=True, null=True, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='test',
            name='text_3',
            field=models.TextField(blank=True, null=True, verbose_name='3'),
        ),
    ]
