# Generated by Django 4.2.2 on 2023-07-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_acceptedtest_text_test_text_4_test_text_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedtest',
            name='text',
            field=models.TextField(default='-', verbose_name='Текст'),
        ),
    ]
