# Generated by Django 4.2.2 on 2023-07-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_ads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'рекламу'},
        ),
    ]
