# Generated by Django 4.2.2 on 2023-07-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_alter_ads_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'рекламу', 'verbose_name_plural': 'реклама'},
        ),
    ]
