# Generated by Django 4.2.2 on 2023-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_ads_status_alter_ads_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='status',
            field=models.CharField(choices=[('1', 'Активный'), ('0', 'Неактивный')], default='1', max_length=255, verbose_name='Статус'),
        ),
    ]
