# Generated by Django 4.2.2 on 2023-07-06 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_alter_ads_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время рассылки'),
        ),
    ]
