# Generated by Django 4.2.2 on 2023-07-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_category_number_test_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='users',
            field=models.ManyToManyField(blank=True, to='backend.botuser', verbose_name='Пользователь'),
        ),
    ]
