# Generated by Django 4.2.2 on 2023-09-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_ads_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='users',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='users',
        ),
        migrations.RemoveField(
            model_name='load',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='users_list',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='users',
        ),
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='tests',
        ),
        migrations.DeleteModel(
            name='AcceptedTest',
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Load',
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
