# Generated by Django 4.2.2 on 2023-09-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_job_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.job', verbose_name='Ваканция'),
        ),
    ]
