# Generated by Django 4.2.2 on 2023-09-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_alter_resume_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='описания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'резюме',
                'verbose_name_plural': 'резюме',
            },
        ),
    ]
