# Generated by Django 4.2.2 on 2023-10-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_category_order_product_shopcard_remove_resume_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template2Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Не трогать!!')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'кнопку',
                'verbose_name_plural': 'кнопки',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
