# Generated by Django 4.2.2 on 2023-10-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_template2button_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAndTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('price_title', models.CharField(max_length=60, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'цену',
                'verbose_name_plural': 'цены',
            },
        ),
        migrations.RemoveField(
            model_name='shopcard',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='template',
            name='text',
            field=models.TextField(unique=True, verbose_name='Текст'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ShopCard',
        ),
        migrations.AddField(
            model_name='priceandtitle',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Товар'),
        ),
    ]
