# Generated by Django 4.2.2 on 2023-10-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_shopcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcard',
            name='status',
        ),
    ]
