# Generated by Django 4.2.2 on 2023-10-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_category1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Сидбанки'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='delivery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип доставка'),
        ),
    ]
