# Generated by Django 4.2.2 on 2023-10-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_alter_template2button_options_mailing_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='message_text_eng',
        ),
    ]
