# Generated by Django 4.2.2 on 2023-10-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_alter_mailing_message_text_ru_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cash',
            field=models.FloatField(default=0, verbose_name='Сумма'),
            preserve_default=False,
        ),
    ]
