# Generated by Django 4.2.2 on 2023-10-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_purchase_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cash',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
    ]
