# Generated by Django 4.2.2 on 2023-10-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_shopcard_status_alter_purchase_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='text',
            field=models.TextField(default=1, verbose_name='тест'),
            preserve_default=False,
        ),
    ]
