# Generated by Django 4.2.2 on 2023-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='schedule',
            field=models.BooleanField(default=False, verbose_name='Уведомления клиенту'),
        ),
    ]
