# Generated by Django 4.2.2 on 2023-10-18 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_purchase_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='category1',
            name='products',
            field=models.ManyToManyField(to='backend.product', verbose_name='Товары'),
        ),
        migrations.RemoveField(
            model_name='category1',
            name='parent',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Ожидает оплаты', 'Ожидает оплаты'), ('Оплачен', 'Оплачен'), ('Отправлен', 'Отправлен')], default='Ожидания', max_length=255, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='category1',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category1', verbose_name='Родительская категория'),
        ),
    ]
