# Generated by Django 4.2.2 on 2023-10-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_category1_products_remove_category1_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category1',
            name='products',
            field=models.ManyToManyField(null=True, to='backend.product', verbose_name='Товары'),
        ),
    ]
